/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Curved_road.glb -o src/utils/CurvedRoad.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CurvedRoad(props) {
  const { nodes, materials } = useGLTF('/assets/models/Curved_road.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Circle002_Circle011-Mesh'].geometry} material={materials['78909C']} />
      <mesh geometry={nodes['Circle002_Circle011-Mesh_1'].geometry} material={materials['1A1A1A']} />
      <mesh geometry={nodes['Circle002_Circle011-Mesh_2'].geometry} material={materials['795548']} />
      <mesh geometry={nodes['Circle002_Circle011-Mesh_3'].geometry} material={materials.FFFFFF} />
    </group>
  )
}

useGLTF.preload('/assets/models/Curved_road.glb')
